export let saved_user_data = {
    user_id: "",
    first_name: "",
    last_name: "",
    username: "",
    email: "",
    phone_number: "",
    daily_distance_goal: 0,
    daily_calorie_goal: 0,
    daily_duration_goal: 0,
    monthly_distance_goal: 0,
    monthly_calorie_goal: 0,
    monthly_duration_goal: 0,
    monthly_workouts_goal: 0,
  }
